name: Build with menuconfig

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新版 Ubuntu 上运行

    steps:
    - name: Checkout code  # 步骤：检出代码
      uses: actions/checkout@v2  # 使用 GitHub 提供的 action

    - name: Install build dependencies  # 步骤：安装编译所需依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev

    - name: Run make alist  # 步骤：执行 make menuconfig
      run: |
        make alist  # 执行 make menuconfig 命令
