name: Build and Release IPKs

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      RELEASE_GITHUB: ${{ secrets.RELEASE_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Build and package projects
      run: |
        mkdir ipks  # 创建目录用于存放 IPK 文件
        for folder in */; do
          if [[ -d "$folder" && ! -L "$folder" ]]; then
            cd "$folder"
            # 替换为每个项目的编译和打包命令，将 IPK 文件放入 ipks 目录中
            make && make install DESTDIR=install_folder && cp install_folder/*.ipk ../ipks/
            cd ..
          fi
        done
    - name: Create release and upload ZIP file
      uses: actions/create-release@v1
      env:
        RELEASE_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0  # Release 的标签名
        release_name: Release 1.0  # Release 的名称
        body: Release description here  # Release 的描述
        draft: false
        prerelease: false
        files: |
          release_ipks.zip  # 将 ZIP 文件添加到 Release 中
